message/urls.py
from django.conf.urls import url, patterns
from message import views

urlpatterns = patterns(
    "",
    url(r'^$', views.index, name='message-index'),
)

page/urls.py
# page url
from django.conf.urls import url, patterns
from page.views import SiteView, IndexView, PageView
#from django.views.generic.base import RedirectView

urlpatterns = patterns(
    "",
    #url(r'^m', RedirectView.as_view(url='/', permanent=False), name='home'),
    url(r'^(?P<site_id>[0-9]+)/$', SiteView.as_view(), name='site-index'),
    url(r'^page/(?P<pk>[0-9]+)/$', PageView.as_view(), name='page-detail'),
)

qing/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from page.views import IndexView

urlpatterns = [
    url(r'^$', IndexView.as_view()),
    url(r'^m/message', include('message.urls', namespace='message')),
    url(r'^m/', include('page.urls', namespace='page')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

message/models.py
from django.db import models
from page.models import Site
from django.forms import ModelForm
# Create your models here.

class Message(models.Model):
    site = models.ForeignKey(Site, related_name='Message', default='1')
    name = models.CharField(max_length=200)
    mobile = models.CharField(max_length=11)
    content = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __unicode__(self):
        return self.name


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = ['site', 'name', 'mobile', 'content']

page/models.py
# -*- coding: utf-8 -*-

from django.db import models
from django.contrib.auth.models import User
from ckeditor.fields import RichTextField
from colorfield.fields import ColorField

# Create your models here.
class Theme(models.Model):
    name = models.CharField(max_length=200, verbose_name='Name')
    value = models.CharField(max_length=200, verbose_name='Value')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Created')
    updated = models.DateTimeField(auto_now=True, verbose_name='Updated')

    def __unicode__(self):
        return self.name


class Template(models.Model):
    name = models.CharField(max_length=200, verbose_name='Name')
    value = models.CharField(max_length=200, verbose_name='Value')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Created')
    updated = models.DateTimeField(auto_now=True, verbose_name='Updated')

    def __unicode__(self):
        return self.name


class Site(models.Model):
    name = models.CharField(max_length=200, verbose_name='Name')
    author = models.ForeignKey(User, related_name="Site", default='1')
    theme = models.ForeignKey(Theme, related_name="Site", default='1', verbose_name='Theme')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Created')
    updated = models.DateTimeField(auto_now=True, verbose_name='Updated')

    def __unicode__(self):
        return self.name

    def site_link(self):
        return '127.0.0.1:8000/m/'+str(self.id)


class Page(models.Model):
    title = models.CharField(max_length=200, verbose_name='Title')
    parent = models.ForeignKey('self', null=True, blank=True, default=None);
    site = models.ForeignKey(Site, related_name="Page", default='1')
    icon = models.ImageField(upload_to='uploads/', blank=True, null=True, default='')
    color = ColorField()
    description = models.TextField(blank=True, verbose_name='Description')
    content = RichTextField(verbose_name='Content', config_name='awesome_ckeditor', blank=True, null=True, default='')
    template = models.ForeignKey(Template, related_name="Page", default='1', verbose_name='Template')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Created')
    updated = models.DateTimeField(auto_now=True, verbose_name='Updated')
    order = models.PositiveIntegerField(default=0, blank=False, null=False)

    def __unicode__(self):
        return self.title

    class Meta(object):
        ordering = ('order',)

    def icon_url(self):
        if self.icon:
            return u'<img src="%s" height="100">' % self.icon.url
        else:
            return ""

    icon_url.short_description = 'Thumb'
    icon_url.allow_tags = True

wechat/models.py
from django.db import models

# Create your models here.

message/forms.py
from django.form import ModelForm
from .models import Message

class MessageForm(ModelForm):
    class Meta:
        model = Message
        #fields = ['site', 'name', 'mobile']
        fields = '__all__'

message/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import MessageForm
#from django.forms.formsets import formset_factory
from django.shortcuts import render_to_response
from page.models import Site

# Create your views here.
def index(request):
    post = request.POST
    site = Site.objects.get(id=post['site'])
    post.site = site
    message = MessageForm(post)
    if message.is_valid():
        message.save()
        return HttpResponse('success')
    else:
        return HttpResponse(message.errors.as_json())

page/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import View, TemplateView, ListView, DetailView
from page.models import Page, Site, Theme

# Create your views here.
class IndexView(TemplateView):
    template_name = "page/home.html"


class SiteView(TemplateView):
    modal = Site

    def get_site(self):
        site = Site.objects.get(id=self.kwargs['site_id'])
        return site

    def get_context_data(self, **kwargs):
        context = super(SiteView, self).get_context_data(**kwargs)
        site = self.get_site()
        context['page_list'] = Page.objects.filter(site=site,parent=None)
        return context

    def get_template_names(self):
        site = self.get_site()
        self.theme = Theme.objects.get(id=site.theme_id)
        return ("page/"+self.theme.value+"/index.html", "page/default/index.html")


class PageView(DetailView):
    model = Page
    context_object_name = "page"

    def get_context_data(self, **kwargs):
        context = super(PageView, self).get_context_data(**kwargs)
        context['child_page'] = Page.objects.filter(parent=self.object.id)
        return context

    def get_template_names(self):
        site = Site.objects.get(id=self.object.site_id)
        theme = Theme.objects.get(id=site.theme_id)
        return ("page/"+theme.value+"/"+self.object.template.value+".html", "page/default/detail.html")

wechat/views.py
from django.shortcuts import render
from . import crypt

# Create your views here.
def index(request):
    if crypt.valid():
        pass
    else:
        return HttpResponse("error")

    return HttpResponse("haha")

page/templates/page/base.html
<!DOCTYPE html>
<!--[if IE 9]><html class="lt-ie10" lang="en" > <![endif]-->
<html class="no-js" lang="en" >
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <!-- If you delete this meta tag World War Z will become a reality -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ MEDIA_URL }}favicon.ico">
    <title>{% block title %}Vertore{% endblock %}</title>

    <!-- If you are using the CSS version, only link these 2 files, you may add app.css to use for your overrides if you like -->
    <link rel="stylesheet" href="{% static 'foundation/css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'foundation/css/foundation.css' %}">

    <!-- If you are using the gem version, you need this only -->
    <link rel="stylesheet" href="{% static 'page/css/page.css' %}">

    <script src="{% static 'foundation/js/vendor/modernizr.js' %}"></script>

  </head>
  <body>
    <div id="nav">
      {% block nav %}
      {% endblock %}
    </div>
    <div id="content">
      {% block content %}
      content
      {% endblock %}
    </div>
    <script src="{% static 'foundation/js/vendor/jquery.js' %}"></script>
    <script src="{% static 'foundation/js/foundation.min.js' %}"></script>
    <script src="{% static 'page/js/page.js' %}"></script>
  </body>
</html>

page/templates/page/contact.html
{% extends "page/base.html" %}
{% block title %}{{ page.title }}{% endblock %}
{% block content %}
<div class="page-contact">
    <div id="map">
        <img width="100%" height="200" src="http://api.map.baidu.com/staticimage?width=280&height=140&zoom=10" />
    </div>
    <div>
        电话：15550005746
        地址：山东济南
    </div>
</div>
{% endblock %}

page/templates/page/default/base.html
<!DOCTYPE html>
<!--[if IE 9]><html class="lt-ie10" lang="en" > <![endif]-->
<html class="no-js" lang="en" >
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <!-- If you delete this meta tag World War Z will become a reality -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ MEDIA_URL }}favicon.ico">
    <title>{% block title %}Vertore{% endblock %}</title>

    <!-- If you are using the CSS version, only link these 2 files, you may add app.css to use for your overrides if you like -->
    <link rel="stylesheet" href="{% static 'foundation/css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'foundation/css/foundation.css' %}">

    <!-- If you are using the gem version, you need this only -->
    <link rel="stylesheet" href="{% static 'page/default/css/page.css' %}">

    <script src="{% static 'foundation/js/vendor/modernizr.js' %}"></script>

  </head>
  <body>
    <div id="nav">
      {% block nav %}
      {% endblock %}
    </div>
    <div id="content">
      {% block content %}
      content
      {% endblock %}
    </div>
    <script src="{% static 'foundation/js/vendor/jquery.js' %}"></script>
    <script src="{% static 'foundation/js/foundation.min.js' %}"></script>
    <script src="{% static 'page/default/js/page.js' %}"></script>
  </body>
</html>

page/templates/page/default/contact.html
{% extends "page/default/base.html" %}
{% block title %}{{ page.title }}{% endblock %}
{% block content %}
<div class="page-contact">
    <div id="map">
        <img width="100%" height="200" src="http://api.map.baidu.com/staticimage?width=280&height=140&zoom=10" />
    </div>
    <div>
        电话：15550005746
        地址：山东济南
    </div>
</div>
{% endblock %}

page/templates/page/default/detail.html
{% extends "page/default/base.html" %}
{% block title %}{{ page.title }}{% endblock %}
{% block content %}
<div class="page-detail">
<span class="page-detail-date">{{ page.created }}</span>
<div>{{ page.content|safe }}</div>
</div>
{% endblock %}

page/templates/page/default/index.html
{% extends "page/default/base.html" %}
{% block title %}首页{% endblock %}
{% block content %}
<ul class="row" id="home">
  {% for page in page_list %}
  <a class="small-6 large-4 columns" href="{% url 'page:page-detail' page.id %}"><div>{{ page.title }}</div></a>
  {% endfor %}
</ul>
{% endblock %}

page/templates/page/default/list.html
{% extends "page/default/base.html" %}
{% block title %}{{ page.title }}{% endblock %}
{% block content %}
<div class="row">
  {% for item in child_page %}
  <a href="{% url 'page:page-detail' item.id %}" class="small-12 large-12 columns">
    {{ item }}
  </a>
  {% endfor %}
</div>
{% endblock %}

page/templates/page/default/message.html
{% extends "page/default/base.html" %}
{% block title %}{{ page.title }}{% endblock %}
{% block content %}
<div class="page-detail">
  <h1>Message</h1>
  {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

  <form data-href="{% url 'message:message-index' %}" method="post" onsubmit="return send(this)">
    <div class="row">
      {% csrf_token %}
      <input type="hidden" name="site" value="{{ page.site.id }}">
      <div class="small-12 columns">
        <div class="small-2 columns">
          <label for="form_name" class="right inline">Name</label>
        </div>
        <div class="small-10 columns">
          <input id="form_name" type="text" name="name">
        </div>
      </div>
      <div class="small-12 columns">
        <div class="small-2 columns">
          <label for="form_mobile" class="right inline">Mobile</label>
        </div>
        <div class="small-10 columns">
          <input id="form_mobile" type="tel" name="mobile">
        </div>
      </div>
      <div class="small-12 columns">
        <div class="small-2 columns">
          <label for="form_content" class="right inline">Content</label>
        </div>
        <div class="small-10 columns">
          <textarea id="form_content" name="content"></textarea>
        </div>
      </div>
      <div class="small-12 columns">
        <div class="small-2 columns"></div>
        <div class="small-10 columns">
          <input class="button" type="submit" value="Submit">
        </div>
      </div>
    </div>
  </form>
</div>
{% endblock %}

page/templates/page/default/message2.html
{% extends "page/default/base.html" %}
{% block content %}
<div class="page-detail">
  <h1>Message</h1>
  {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
  <form action="{% url 'message:message-index' %}" method="post">
    {% csrf_token %}
    <table>
      {{ formset }}
    </table>
    <input type="submit" value="submit">
  </form>
</div>
{% endblock %}

page/templates/page/default/pay.html
{% extends "page/default/base.html" %}
{% block title %}{{ page.title }}{% endblock %}
{% block content %}
pay
{% endblock %}

page/templates/page/detail.html
{% extends "page/base.html" %}
{% block title %}{{ page.title }}{% endblock %}
{% block content %}
<div class="page-detail">
<span class="page-detail-date">{{ page.created }}</span>
<div>{{ page.content|safe }}</div>
</div>
{% endblock %}

page/templates/page/home.html
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml">
  <head>
    {% load staticfiles %}
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Qing platform</title>
    <meta name="author" content="Alvaro Trigo Lopez">
    <meta name="description" content="">
    <meta name="keywords"  content="">
    <meta name="Resource-type" content="Document">


    <link rel="stylesheet" type="text/css" href="{% static 'fullpage/jquery.fullPage.css' %}">

    <script src="{% static 'foundation/js/vendor/jquery.js' %}"></script>

    <script type="text/javascript" src="{% static 'fullpage/jquery.fullPage.min.js' %}"></script>
    <script type="text/javascript">
      $(document).ready(function() {
      $('#fullpage').fullpage({
      sectionsColor: ['#1bbc9b', '#4BBFC3', '#7BAABE', 'whitesmoke', '#ccddff'],
      anchors: ['firstPage', 'secondPage', '3rdPage', '4thpage', 'lastPage'],
      menu: '#menu',
      css3: true,
      scrollingSpeed: 1000
      });

      $('html').click(function(){
      $('#examplesList').hide();
      });
      });
    </script>

  </head>
  <body>

    <div id="fullpage" style="text-align:center;">

      <div class="section active" id="section0">
        <h1>Hello</h1>
      </div>
      <div class="section" id="section1">
        <h2>Do you know...</h2>
      </div>
      <div class="section" id="section2">
        <h2>Who am I ?</h2>
      </div>
      <div class="section" id="section3">
        <h2>You guess :)</h2>
      </div>
    </div>
  </body>
</html>

page/templates/page/index.html
{% extends "page/base.html" %}
{% block title %}首页{% endblock %}
{% block content %}
<ul class="row" id="home">
  {% for page in page_list %}
  <a class="small-6 large-4 columns" href="{% url 'page:page-detail' page.id %}"><div>{{ page.title }}</div></a>
  {% endfor %}
</ul>
{% endblock %}

page/templates/page/list.html
{% extends "page/base.html" %}
{% block title %}{{ page.title }}{% endblock %}
{% block content %}
<div class="row">
  {% for item in child_page %}
  <a href="{% url 'page:page-detail' item.id %}" class="small-12 large-12 columns">
    {{ item }}
  </a>
  {% endfor %}
</div>
{% endblock %}

page/templates/page/pay.html
{% extends "page/base.html" %}
{% block title %}{{ page.title }}{% endblock %}
{% block content %}
pay
{% endblock %}

page/templates/page/simple/base.html
<!DOCTYPE html>
<!--[if IE 9]><html class="lt-ie10" lang="en" > <![endif]-->
<html class="no-js" lang="en" >
  <head>
    {% load staticfiles %}
    <meta charset="utf-8">
    <!-- If you delete this meta tag World War Z will become a reality -->
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="shortcut icon" href="{{ MEDIA_URL }}favicon.ico">
    <title>{% block title %}Vertore{% endblock %}</title>

    <!-- If you are using the CSS version, only link these 2 files, you may add app.css to use for your overrides if you like -->
    <link rel="stylesheet" href="{% static 'foundation/css/normalize.css' %}">
    <link rel="stylesheet" href="{% static 'foundation/css/foundation.css' %}">

    <!-- If you are using the gem version, you need this only -->
    <link rel="stylesheet" href="{% static 'page/simple/css/page.css' %}">

    <script src="{% static 'foundation/js/vendor/modernizr.js' %}"></script>

  </head>
  <body>
    <div id="content">
      {% block content %}
      content
      {% endblock %}
    </div>
    <script src="{% static 'foundation/js/vendor/jquery.js' %}"></script>
    <script src="{% static 'foundation/js/foundation.min.js' %}"></script>
    <script src="{% static 'page/js/page.js' %}"></script>
  </body>
</html>

page/templates/page/simple/index.html
{% extends "page/simple/base.html" %}
{% block title %}首页{% endblock %}
{% block content %}
hhh
{% endblock %}